### ISSUE TITLE
When Running MetaPathPredict script and met some errors

### ISSUE THREAD

**Issue by microbial-cookie** [d-mcgrath/MetaPathPredict#7] opened 2024-07-19 20:45 UTC
Hi developers,

MetaPathPredict is a great tool for predicting the KEGG module in the MAGs, but when I run it, and met some errors. Could help me to check it and solve this problem, Thanks.
![image](https://github.com/user-attachments/assets/0d3d175c-3159-44ef-b742-dd16f7235f51)

**Comment by d-mcgrath** [comment] 2024-07-20 17:57
Hi Ruiwen, thank you for letting us know about this issue. I'm working on reproducing this error and will post a fix as soon as I figure it out.

**Comment by d-mcgrath** [comment] 2024-07-20 18:23
Ruiwen, could you please email me (mcgrath1 [at] mit.edu) the annotation file you are working with? I'm not able to reproduce the issue with dram files on my end. Also, did you install all the Python packages required by MetaPathPredict with the version numbers specified in the installation instructions?

**Comment by microbial-cookie** [comment] 2024-07-24 17:36
Hi David,

Sorry to the late reply, I reinstall all the Python packages required by MetaPathPredict, and it worked well. I think the version of Python packages didn't match the MetaPathPredict. Very great tool to annotate the KEGG modules. Thanks

**Comment by d-mcgrath** [comment] 2024-07-25 18:07
Hi Ruiwen,

That's great to hear! I'm glad it's working for you now. Feel free to reach out if you run into any other issues. Going to close this

**Closed as completed** 2024-07-25 18:07 UTC
